#:schema node_modules/wrangler/config-schema.json
name = "sublink-workerr"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "09f8a01346b2454f93ad99f60e6120e3" }
]

[assets]
directory = "./public"
